### ISSUE TITLE
Calling html_to_pdf results in a TypeError

### ISSUE THREAD

**Issue by lnadi17** [mikahama/pdfy#4]
When I run this code from python shell
```python
>>> from pdfy import Pdfy
>>> p = Pdfy()
>>> p.html_to_pdf("test.html", "test.pdf")
```
I get this error
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfy\pdfy.py", line 58, in html_to_pdf
    pdf_data = self.chrome.Page.printToPDF(**options)["result"]["data"]
TypeError: tuple indices must be integers or slices, not str
```
It goes away when I change this line
```python
pdf_data = self.chrome.Page.printToPDF(**options)["result"]["data"]
```
To this
```python
pdf_data = self.chrome.Page.printToPDF(**options)[0]["result"]["data"]
```

**Comment by mikahama** [comment]
Thank you for reporting this. It was a bug apparently because of a PyChromeDevTools updated. I fixed it and the new version is on pypi
